# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('io.grpc', 'grpc-netty-shaded', '1.68.0')
require_jar('io.grpc', 'grpc-protobuf', '1.68.0')
require_jar('io.grpc', 'grpc-services', '1.68.0')
require_jar('io.grpc', 'grpc-stub', '1.68.0')
require_jar('com.google.protobuf', 'protobuf-java-util', '4.28.2')
require_jar('io.opentelemetry.instrumentation', 'opentelemetry-grpc-1.6', '1.32.0-alpha')
require_jar('com.google.guava', 'guava', '33.3.1-jre')
require_jar('io.opentelemetry', 'opentelemetry-api', 'null')
require_jar('io.opentelemetry', 'opentelemetry-sdk', '1.42.1')
require_jar('io.opentelemetry', 'opentelemetry-exporter-zipkin', '1.42.1')
require_jar('io.opentelemetry.instrumentation', 'opentelemetry-grpc-1.6', 'null')
require_jar('io.opentelemetry.semconv', 'opentelemetry-semconv', 'null')
require_jar('org.logstash.plugins.input.grpc', 'logstash-input-grpc', '0.0.1')
